### ISSUE TITLE
how about generalization of sincNet ?

### ISSUE THREAD

**Issue by eeric** [mravanelli/SincNet#13]
First, thanks for your contribution.
In your expriment, Classification Error Rates - CER% for speaker-id task and Equal Error Rate - EER% for speaker verification used, howeve, at present, deep feature representition and similarity scores were used to speaker recognition, so whether if should explain generalization of sincNet from A dataset training to B dataset testing.

**Comment by mravanelli** [comment]
In the studies that we have conducted so far (for both speaker and speech recognition) we have done training and test on the same dataset (as often done in the speech/speaker recognition community). We didn't check so far cross-dataset performance. I think the behavior is similar to that of standard neural networks: if the datasets A and B are similar you might have good performance, otherwise, you likely have a performance drop. We are currently working on some adaptation strategies (that will probably be an object of a future paper) in order to perform a quick unsupervised adaptation of SincNet to conditions very different from that seen during training. The big advantage of SincNet if that the first convolutional layers is based on a few hundreds of learnable parameters only, while standard CNNs are based on thousands of them. This feature could make adaptation much easier!

**Comment by eeric** [comment]
alright, hope you successfully.

**Comment by eeric** [comment]
I appreciated your sinc_conv.

**Comment by eeric** [comment]
nevertheless, sentence embedding a little more in SincNet.forward in dnn_models.py
