### ISSUE TITLE
Performance on larger datasets

### ISSUE THREAD

**Issue by seandickert** [mravanelli/SincNet#15]
Hi Mirco,

I'm curious if you had to make any adjustments to the structure of the model to handle the >2k speakers in LibriSpeech? I've been attempting to fit a model on >3k speakers, and the Sentence Classification Error doesn't drop below ~50%.  I have ~3min of speech per speaker.

Could you provide the res.res file for LibriSpeech that you provided for TIMIT?

**Comment by mravanelli** [comment]
Hi,
In exp/SincNet_Librispeech/res.res I added the results I have obtained with SincNet on the Librispeech dataset, while in cfg/SincNet_Librispeech.cfg I added the config file. As you can see from the config file, the best system on Librispeech is different from that used for TIMIT. In particular, we are using 8kHz speech signals (we use only the bandwidth from 0 to 4 kHz that contains the most important information for speaker-id), we have 3 convolutional layers followed by 3 fully connected layers of 2048 neurons, and we are using a larger context of 375 ms. Which dataset are you currently using? In Librispeech we obtained such a very good performance because it is a very clean and noiseless task.

**Comment by seandickert** [comment]
Thanks for the response and posting the Librispeech configs and results.  I'm using TIMI + Libri + some calls i've recorded. Unfortunately the calls can be of varying quality.

A few questions from what you've posted:
- What's the purpose of moving the last FC layer from the DNN section of the config to the class section? As far as I can tell, the effect will be the same.

- Did you use the 360hour librispeech dataset?

- For the Libri EER, could you describe how you ran the test?  Were the speakers used held out from the training speakers?  Did you do a 1 sentence vs 1 sentence comparison, or did you combine all dvectors for all sentences for a speaker prior to comparison?

- So far, it appears that because SincNet is utterance based, it may be susceptible to unclean calls. That is, calls with loud sounds which aren't speech. Do you think it might be useful to use SincNet as the feature extractor, then train a second model which considers all utterances at once? Something such as a SincNet-RNN or SincNet-3DCNN?

**Comment by seandickert** [comment]
With regards to # 4 in that list, what I mean is that because SincNet is utterance based, in classification, each of the utterances, including voice and loud non-speech sound, will be weighted and considered equally when determining the likelihood of the speaker. Similarly, when doing a d-vector comparison, loud non-speech utterances will be averaged with the speech utterances prior to comparison.  However, if we pass all of the utterances through to something like a 3D CNN, would that CNN be able to learn something like non-speech filters (same idea for an RNN).

**Comment by mravanelli** [comment]
Hi,
let me answer you question in the following:
1- It is the same actually. Doing that allows us to write a code a little
bit more clean when we would like to calculated the d-vectors or when want
to perform multi-task learning.
2- With librispeech we used all the speakers, but only taking 10-15 seconds
of material for each. At the end we are only using about 8/10 hours of
speech material. This is more than enough for a simple dataset like
librispeech. Librispeech contains a lot of speakers (more than 2400), but
it is still a very easy dataset because it is perfectly clean and there
aren't channel mismatch issues. This was a perfect task to initially show
the effectiveness of SincNet, but we are now trying our SincNet on more
realistic tasks, like VoxCeleb.
3- For speaker verification the enrollment and test data are taken for both
dev and test speakers. We sum up all the enrollment d-vectors for each
speaker( we thus have 1 enrollment d-vector for each speaker). Then we
compare each d-vector computed on each test sentence with the enrollment
d-vector prototype. This solution turned out to work well for librispeech.
4. Yes, this totally make sense. There are some frames than are more
important than others to detect the speaker identity. For instance, in the
repository we upload a simple d-vector computation code that only sums up
d-vectors if there is enough energy in the frame. This is a simple solution
that allows people to avoid people to compute d-vectors on silence regions.
Of course you can think about something more complex. One idea is to use an
RNN, while another (sometimes explored in some speaker-id papers) consists
in using an attention model.

Let me know if my answers are clear enough...

Best,

Mirco

**Comment by seandickert** [comment]
Thanks Mirco, I'm experimenting with adding an RNN and/or attention network now.

I'm going to open a separate issue about the Libri dataset, as I'm trying to reproduce those results, so feel free to close this one.
