### ISSUE TITLE
Questions aiming experiments replication

### ISSUE THREAD

**Issue by lucgeo** [mravanelli/SincNet#2]
I really appreciate you released the paper together with the source code. Also, I have few questions:
1. I have plotted the "err_te" from "res.res" file and it seems to be different than Fig. 4 from the paper.  Fig. 4 contains values below 0.4% FER, while the "res.res" file has a minimum value for "err_te" equal to 0.410. Why?
2. If "err_te_snt" represents the classification error, that means the classification error is equal to 0.57% after 360 epochs (according to "res.res" file). In the paper it is equal to 0.85% (Table 1). Why?
3. What is the experimental setup for speaker verification?

Thank you!

**Comment by mravanelli** [comment]
Thank you for the interest into this project.  
In general, some small oscillations in the performance are physiological and are mainly due to different initializations in different machines.  As you can see from the res.res" file, when the network converges (see epochs 288-360) there are still some oscillations ranging from (1.4% to 0.57%). To have more "stable" and reliable results, in the paper we run our system many times (e.g, 10 times) and we averaged the performance at epoch 360. If you do something like that you should see a number close to what we reported in the paper.
