### ISSUE TITLE
Training on GPU got error on CPU decoding

### ISSUE THREAD

**Issue by hdubey** [mravanelli/SincNet#34]
I got this error while doing d_vector extraction. Is D-vector output of 2nd CNN layers?   Error seems to be due to availability of Torch GPU version and not CPU. How did you handle in your case? Thanks! Below is error message:

 import torch
  File "anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)

**Comment by mravanelli** [comment]
This seems to be a more basic error due to the GLIBC. Could you try to
upload your python to 3.7 and you pytorch to 1.0?

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
