### ISSUE TITLE
Absolute value of the output of sinc-based convolutions?

### ISSUE THREAD

**Issue by hbredin** [mravanelli/SincNet#4]
`torch.abs` is applied to the output of sinc-based convolutions. 

https://github.com/mravanelli/SincNet/blob/488c9822e94b1bbfdbf25ba2ca5986632f952909/dnn_models.py#L312-L313

Why is that? I coudn't find an explanation in the paper.

**Comment by mravanelli** [comment]
Hi Hervé,
we tried many different alternatives at this level and experiments are still running to find better solutions.  For instance, we recently compared the performance with  and without  the abs function you pointed out.  The reason why it could make sense to add an abs function here, is that standard max-pooling only looks into the positive samples of the filtered signal, while with abs we basically consider the envelope of it. This would allow the network to extract features more related to the “energy” or “envelope” of the signal,  resembling “more closely” the standard pipeline used for extracting standard fbank or mfcc features. Actually, the standard fbanks is still quite different since we average the spectrum within rectangular filters. From my experiments, however, I saw that doing average pooling at this level works slightly worse than max pooling.

**Comment by hbredin** [comment]
Thanks for the clarification -- it would make a nice addition to the paper and definitely help others reproduce your experiment.

Here is my (slightly more pytorchic) version of `SincConv` that can be used as a drop-in replacement for `torch.nn.Conv1d`: https://gist.github.com/hbredin/c3bfa80f8f71181c2d499167d297f181

**Comment by mravanelli** [comment]
Great job! thank you!

**Comment by Rachine** [comment]
It seems that the addition of this abs operation is very important for fast convergence!
