### ISSUE TITLE
performance on Voxceleb1? 

### ISSUE THREAD

**Issue by linjucs** [mravanelli/SincNet#56]
How about the performance

**Comment by linjucs** [comment]
Just notice this paper https://arxiv.org/pdf/1812.00271.pdf

**Comment by linjucs** [comment]
Hi Mirco,

Thanks for sharing this code. Very cool toolkit. Recently I am working on Sincnet on voxceleb1. But the performance is not well. Could you please give me some suggestions? I removed the silence using webrtcvad.

Thanks.
Lin


epoch 0, loss_tr=6.254185 err_tr=0.976379 loss_te=6.414922 err_te=0.987285 err_te_snt=0.973458
epoch 8, loss_tr=3.098647 err_tr=0.626692 loss_te=6.009328 err_te=0.905808 err_te_snt=0.778572
epoch 16, loss_tr=2.121552 err_tr=0.451692 loss_te=5.882671 err_te=0.857070 err_te_snt=0.673373
epoch 24, loss_tr=1.655752 err_tr=0.362991 loss_te=5.679876 err_te=0.823700 err_te_snt=0.611926
epoch 32, loss_tr=1.369494 err_tr=0.305188 loss_te=5.745930 err_te=0.811133 err_te_snt=0.595928
epoch 40, loss_tr=1.167458 err_tr=0.263594 loss_te=5.790279 err_te=0.797424 err_te_snt=0.579203
epoch 48, loss_tr=1.023051 err_tr=0.233562 loss_te=5.812299 err_te=0.780975 err_te_snt=0.566356
epoch 56, loss_tr=0.911310 err_tr=0.210032 loss_te=5.868678 err_te=0.771352 err_te_snt=0.541268
epoch 64, loss_tr=0.828135 err_tr=0.192578 loss_te=5.780817 err_te=0.767120 err_te_snt=0.550358
epoch 72, loss_tr=0.761099 err_tr=0.177930 loss_te=6.150887 err_te=0.759397 err_te_snt=0.538965
epoch 80, loss_tr=0.707083 err_tr=0.166238 loss_te=5.915407 err_te=0.758966 err_te_snt=0.542359

**Comment by mravanelli** [comment]
Hi,
one risk with SincNet is overfitting and apparently you are observing this
issue as well. SincNet can tune its filters according to the training
conditions and if such conditions are very different from test ones you can
see overfitting. A good property, however, is it possible to adapt SincNet
very quickly to the new domain if you have adaptation data (this is due to
the drastically reduced number of parameters). Unfortunately, this is not
possible with VoxCeleb. To make a SincNet system working on this dataset, a
lot of efforts should be devoted to avoid overfitting. In our case, we have
achieved good performance by coupling SincNet with a semi-supervised
strategy that acts as a powerful regularizer (see
https://arxiv.org/abs/1812.00271). We are also working on other ideas to
help SincNet fighting overfitting.

Best,

Mirco

**Comment by linjucs** [comment]
Thanks man. I will try to address overfitting problem.

**Comment by brealisty** [comment]
> Thanks man. I will try to address overfitting problem.

I also met this problem, in my own data, could you give me some advices to address overfitting?

**Comment by Tommy-Ngx** [comment]
@linjucs can you please share your work with voxceleb1? my email is tommyfederation@gmail.com. I am trying to test it with vox1 as well. Do you try verification task? I don't know how to deal with that? thank you very much!
