### ISSUE TITLE
Computational Efficiency Through Symmetric Convolutions

### ISSUE THREAD

**Issue by KnurpsBram** [mravanelli/SincNet#59]
The paper mentions symmetry of the convolutional filters as a benefit because 'we can perform convolution in a very efficient way by only considering one side of the filter and inheriting the results for the other half'. Sounds nice! How is this reflected in the implementation? The F.conv1d() function is called with a kernel of full width. Does cudnn backend somehow recognize the symmetry in the filter and change its algorithm accordingly?

I do see a difference in the classes sinc_conv and SincConv_fast, but the difference is only in the construction of the filters from the computed frequency bands (where the slower one uses a for-loop), not in the convolution itself.

I'm very interested in this symmetry property, could you explain or reference some additional material on it? thanks!

**Comment by mravanelli** [comment]
Hi,
thank you very much for your interest in my work.
As you pointed out, the possible computational advantages are in the filter
construction because you can compute only half of the SincNet function and
inherit it for the second half of the filter (note that the filter is
symmetric, but the input signal isn't and we thus have to compute anyway
the full convolution.). After the submission we noticed that this has  a
minimal impact only on the computation time, mainly because GPUs
parallelize very efficiently these computations. It can have more impact on
small footprint devices. The paper should be changed to give less emphasis
to this aspect.

Best,

Mirco

**Comment by KnurpsBram** [comment]
I see. Thanks for clearing that up! :)
